### PR TITLE
Issue7 Trace.WriteLine

### PR DESCRIPTION
**Pull request by dasjestyr**
Using the specific trace methods for info, warn, and error allow visual studio to intercept the log and append some crud to the front of it which really garbles the output. Since none of the params were being used to begin with, I just switched everything to WriteLine in order to preserve the formatting:

Before:

> 2017-07-31 13:37:17.840 -07:00 [Verbose] This is a verbose message
> 2017-07-31 13:37:17.871 -07:00 [Debug] This is a debug message
> TraceWriteLineExample.exe Information: 0 : 2017-07-31 13:37:17.872 -07:00 [Information] This is an info message
> TraceWriteLineExample.exe Warning: 0 : 2017-07-31 13:37:17.873 -07:00 [Warning] This is a warning message
> TraceWriteLineExample.exe Error: 0 : 2017-07-31 13:37:17.874 -07:00 [Error] This is an error message
> TraceWriteLineExample.exe Error: 0 : 2017-07-31 13:37:17.875 -07:00 [Fatal] This is a fatal message

After:

> 2017-07-31 13:39:09.630 -07:00 [Verbose] This is a verbose message
> 2017-07-31 13:39:09.655 -07:00 [Debug] This is a debug message
> 2017-07-31 13:39:09.656 -07:00 [Information] This is an info message
> 2017-07-31 13:39:09.657 -07:00 [Warning] This is a warning message
> 2017-07-31 13:39:09.657 -07:00 [Error] This is an error message
> 2017-07-31 13:39:09.658 -07:00 [Fatal] This is a fatal message

### CODE REVIEW

**Comment by nblumhardt** [comment]
Looks great, thanks 👍 

The build seems to be expecting the old project system - updating `appveyor.yml` using the content from https://github.com/serilog/serilog-sinks-console/blob/dev/appveyor.yml should fix it.

**Comment by dasjestyr** [comment]
Updating the build image didn't work. I think it's the dotnet cli version that's probably clashing at the moment. I see that it's downloading a specific version and trying to use it. When you said to use the console sink's build config, were you being literal as in use the whole thing?

**Comment by nblumhardt** [comment]
You'll need to update the entire appveyor.yml I think - just replacing the contents should do it. Note the old one is using the pre-RTM tools :-) 👍

**Comment by dasjestyr** [comment]
touchdown.

**Comment by nblumhardt** [comment]
Awesome :-) 👍

**Pull request merged**
